services:
  minecraft:
    image: amazoncorretto:21
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25565:25565/udp"
      - "19132:19132/udp" # optional - used for bedrock (geyser-spigot)
    volumes:
      - ./:/data # mount vol for curr directory as `/data`
    restart: unless-stopped
    # replace `paper.jar` with minecraft server jar file
    command: /bin/sh -c "cd /data && java -Xms8G -Xmx8G -jar server.jar --nogui"
    # The following allow `docker attach container minecraft server` to work
    stdin_open: true
    tty: true
