services:
  minecraft:
    env_file:
      - path: ./.env
        required: true
    image: amazoncorretto:${IMAGE_VERSION}
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25565:25565/udp"
      - "19132:19132/udp" # optional - used for bedrock (geyser-spigot)
    volumes:
      - ./:/data # mount vol for curr directory as `/data`
    restart: unless-stopped
    command: /bin/sh -c "cd /data && java -Xms${MIN_JAVA_GB}G -Xmx${MAX_JAVA_GB}G -jar ${SERVER_FILE_NAME} --nogui"
    # The following allow `docker attach container minecraft-server` to work
    stdin_open: true
    tty: true
  # build image locally
  plugin-updater:
    build:
      context: microservices/plugin-updater
      dockerfile: Dockerfile
    pull_policy: build
    container_name: minecraft-plugin-updater
    volumes:
      - ./:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped